version: '3.8'

services:
    account_database:
        container_name: account_database
        image: postgres:13-alpine
        restart: always
        volumes:
          - rocweb_account_data:/var/lib/postgresql/data
        ports:
          - 5434:5432
        environment:
          - "TZ=Asia/Baku" 
        env_file:
          - ./.env.dev
      
    account_web:
        container_name: account_web
        build: .
        command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8003"
        environment:
          - ENV=dev
        volumes:
          - .:/app
          - ./logs:/var/log
        ports:
          - 8003:8003
        restart: always

volumes:
  rocweb_account_data: