version: '3.8'

services:
    database:
        container_name: backend_db
        image: postgres:13-alpine
        restart: always
        volumes:
          - db_data:/var/lib/postgresql/data
        ports:
          - 5434:5432
        environment:
          - "TZ=Asia/Baku" 
        env_file:
          - ./.env.dev
      
    web:
        container_name: backend_web
        build: .
        command: bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 8003"
        environment:
          - ENV=dev
        volumes:
          - .:/app
          - ./logs:/var/log
        ports:
          - 8003:8003
        restart: always

volumes:
  db_data: