"""Add is_active field

Revision ID: 907e86e460d5
Revises: e2a32e17a663
Create Date: 2023-04-12 15:01:58.927050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907e86e460d5'
down_revision = 'e2a32e17a663'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
