"""Create category

Revision ID: cf3388347129
Revises: 18ee0fb39a9a
Create Date: 2023-05-06 09:43:26.593252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3388347129'
down_revision = '18ee0fb39a9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
